# Generated by Django 5.2.15 on 2026-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('leave', 'Leave')], default='present', max_length=20),
        ),
    ]
